# Generated by Django 2.2.13 on 2021-01-15 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('douban', '0005_auto_20210115_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='update_at',
        ),
    ]
