# Generated by Django 2.2.13 on 2021-01-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('douban', '0007_auto_20210115_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='nickname',
            field=models.CharField(max_length=100, verbose_name='昵称'),
        ),
    ]
