# Generated by Django 2.2.13 on 2021-01-16 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('douban', '0008_auto_20210115_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=50, verbose_name='电影名')),
                ('nickname', models.CharField(max_length=100, verbose_name='昵称')),
                ('rate', models.CharField(max_length=5, verbose_name='评分')),
                ('content', models.CharField(max_length=500, verbose_name='评论内容')),
                ('comment_date', models.DateTimeField(verbose_name='评论日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
    ]
