# Generated by Django 2.2.13 on 2021-01-16 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('douban', '0009_comment_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_test',
            name='content',
            field=models.CharField(max_length=1000, verbose_name='评论内容'),
        ),
    ]
